### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by wafardev**
The "Close" button on line 158 has been changed to "Sign in" and url subdomain removed.
Also, it it only possible to create accounts using the DEBUG flag.

### CODE REVIEW

**Comment by GaspardCulis** [comment]
Hi, thanks for contributing. But your python formatter changed a lot of things in the code. I'm using the [black](https://black.readthedocs.io/en/stable/index.html) formatter for this project. I'll try to fix this myself

**Comment by GaspardCulis** [comment]
Spent the afternoon rewriting everything lol. Now works 50% the time with new domain

**Comment by wafardev** [comment]
Hey, this minor fix fortunately works but for some reason, only when the chromedriver is not in headless mode. Is there any fix to it?
Also, I’ve noticed that elevenlabs displays randomly 2 different login pages, either the inputs are on the left-hand side or on the right with a wave animation on the left. It seems that it only works for the second option.

Thanks,
wafardev
________________________________
De : Gaspard Culis ***@***.***>
Envoyé : Saturday, August 17, 2024 2:48:03 PM
À : GaspardCulis/elevenlabs-unleashed ***@***.***>
Cc : GAJEWICZ Rafaou ***@***.***>; Author ***@***.***>
Objet : Re: [GaspardCulis/elevenlabs-unleashed] Minor fix (PR #30)


Hi, thanks for contributing. But your python formatter changed a lot of things in the code. I'm using the black<https://black.readthedocs.io/en/stable/index.html> formatter for this project. I'll try to fix this myself

**Comment by GaspardCulis** [comment]
Yes I noticed that. For the headless mode not working I guess in that mode you are more likely to get categorized as a bot bcz the browser context is different.
And for that different login page thing I guess they are currently testing new updates that are tested on people half the time, in a few weeks we'll only have the first case (wave anim on the right).

**Pull request closed without merging**
